### PR TITLE
C3DC-367

### PR DESCRIPTION
**Pull request by Senait7-ux**
Facet-filter version updated

### CODE REVIEW

**Comment by Senait7-ux** [comment]
https://github.com/CBIIT/bento-c3dc-frontend/pull/67

**Review by huuaho — APPROVED** [review]

**Comment by huuaho** [comment]
LGTM

**Comment by iksheth** [comment]
LGTM, But 1.1.0 branch is not upto date. So, Let's not merge it for now.

**Comment by iksheth** [comment]
Changed base branch, 1.0.1 (Release 2 Branch) -> 1.2.0 (Release 3 Branch)

**Pull request merged**
