### PR TITLE
C3DC-1027

### PR DESCRIPTION
**Pull request by Senait7-ux**
[C3DC-1058](https://tracker.nci.nih.gov/browse/C3DC-1058) is also handled with this branch.

### CODE REVIEW

**Comment by Senait7-ux** [comment]
https://github.com/CBIIT/bento-c3dc-frontend/pull/165

**Comment by iksheth** [comment]
Related to 823

**Comment by iksheth** [comment]
Merge Conflicts.

**Comment by Senait7-ux** [comment]
> Merge Conflicts.

resolved

**Review by iksheth — APPROVED** [review]

**Pull request merged**
