### PR TITLE
Study Detail Page Finalized 

### PR DESCRIPTION
**Pull request by Senait7-ux**
[C3DC-526](https://tracker.nci.nih.gov/browse/C3DC-526)

### CODE REVIEW

**Comment by huuaho** [comment]
Please resolve the following issues that appear when compiling prior to merge

./src/pages/studies/studyDetailController.js
Line 1: 'useEffect' is defined but never used no-unused-vars
Line 1: 'useState' is defined but never used no-unused-vars
Line 4: 'StudyView' is defined but never used no-unused-vars
Line 9: 'connect' is defined but never used no-unused-vars
Line 17: Unnecessarily computed property ["study_id"] found no-useless-computed-key

./src/pages/studies/studyDetailView.js
Line 45: img elements must have an alt prop, either with meaningful text, or an empty string for decorative images jsx-a11y/alt-text
Line 47: img elements must have an alt prop, either with meaningful text, or an empty string for decorative images jsx-a11y/alt-text
Line 66: img elements must have an alt prop, either with meaningful text, or an empty string for decorative images jsx-a11y/alt-text
Line 96: Expected '===' and instead saw '==' eqeqeq
Line 208: Duplicate key 'height' no-dupe-keys

**Comment by huuaho** [comment]
According to the [figma design](https://www.figma.com/file/ScHHKMHDxcHeGDLbxiV9zD/C3DC-Homepage?type=design&node-id=2293-4340&mode=design&t=UYWLM6H4YyaVCtik-4)

The Study Code should be aligned with the C3DC Studies
image

The font used is Lato when it should be Poppins, certain font colors are off as well (e.g. numbers for stats)
For controlling the styling of the 'Overview' I recommend not using an h1 tag as it has a bunch of predefined styles within it.
image

**Comment by huuaho** [comment]
Please observe the alignment of the breadcrumb, the studies header, and the study code within the figma design.
image

- The three should be aligned together
- Overview should come after these three in alignment
- The spacing between the Overview and the description requires more padding
- We are missing this blue divider 
image
image

**Comment by Senait7-ux** [comment]
@huuaho
** The three should be aligned together
  What do you mean by the three?
** The breadcrumb requires updated styling
 the breadcrumbs are updated based on the figma
** Overview should come after these three in alignment
 again what do we mean by the three?
** The spacing between the Overview and the description requires more padding
 the spacing has been addressed
** We are missing this blue divider
 and what do you mean by the blue divider? is it the scroll bar? if so the scroll bar is there and only becomes visible when required / when there is more content than it can show with in the screen

**Comment by huuaho** [comment]
Apologies due to the format of the images and the text the first line was cut off.

By "the three" I was referring to the first statement...
`Please observe the alignment of the breadcrumb, the studies header, and the study code within the figma design.`

The breadcrumb's font does not seem to match the Figma's

The blue divider is the blue bar that appears within the vertical line divider and is currently selected within the screenshot

**Comment by Senait7-ux** [comment]
@huuaho I have made updates based on your comments, however I think you maybe referring to the scroll bar when you said the blue divider, let me know if i misunderstood it.  Take a look at the below screenshot to see how everything looks on my end, Thank you!
image

**Comment by huuaho** [comment]
Yes! You're right! That blue bar was the scrollbar. I was confused. 

Your changes look good.

There are two changes from the chat...
- in regards to updating the inject.env issue. Please implement this from that branch as well as re-integrate the /study/:studyid functionality for the 2 level URLs
- And update the line to include the font 'Public Sans' for the breadcrumb.

**Review by huuaho — APPROVED** [review]
Tested locally, LGTM

**Pull request merged**
